### ISSUE TITLE
Remaining 9.0 todo

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/MassEffectModManager#434]
Just some things left to do:
- [x] Mods have restore from ME3Tweaks even though they are not on the updater service
- [x] Texture modded files can be restored even though they shouldn't be with new tracking changes
- [x] Restore game autopanel needs % for texture tagged packages
- [x] Mod search box in main window should track open close state
- [x] Add menu item for running target merges
- [x] Batch Installer: Dialog when desc/name is missing on save
- [x] Handle texture mod import from drag/drop of .mem (LE only)
- [x] Disable dlmgr branch features in release builds
- [x] Settings text box disabled/watermark colors
- [x] LE - deleting DLC mod code seems to indicate it's showing references to ALOT mod
- Probably more

**Comment by DropTheSquid** [comment]
- [x] Disallow compiling a merge mod with assets not in the same folder as the json being compiled. (I have done this a bit with subfolders, but it doesn't decompile them into the same subfolders, so it fails to recompile)

**Comment by Herobrine24** [comment]
Failed Mods Dialog:
- [x] Add refresh/reload button
- [x] Add button to open selected mod's folder

**Comment by Mgamerz** [comment]
> * [x]  Disallow compiling a merge mod with assets not in the same folder as the json being compiled. (I have done this a bit with subfolders, but it doesn't decompile them into the same subfolders, so it fails to recompile)

This has been implemented, but I am not going to check it off until you can test when I post the next alpha.

**Comment by DropTheSquid** [comment]
> > * [x]   Disallow compiling a merge mod with assets not in the same folder as the json being compiled. (I have done this a bit with subfolders, but it doesn't decompile them into the same subfolders, so it fails to recompile)
> 
> This has been implemented, but I am not going to check it off until you can test when I post the next alpha.

Confirmed this works.

**Comment by DropTheSquid** [comment]
- [x] Check the result of game restore when installing batch which has a restore step, abort if it fails.

**Comment by Mgamerz** [comment]
- [x] LE2 (and LE3) squadmate outfit merge generation should only source from basegame, official DLC, or community patch/unofficial patch folders, so it doesn't pull in replacement. Perhaps notify if patch is not available, or source from the mod library.

**Comment by Mgamerz** [comment]
- [x] Checks in deployment should adjust the title bar and message in list dialog according to the contents that will be displayed, as they are misleading if it's just information.

**Comment by Mgamerz** [comment]
- [x] Ensure all windows use proper colored theme for title bars. Starter Kit for example does not.
- [x] BatchMod.cs has 'ModName' for serialization but library and editor for some reason are not using it. It seems to exist to help provide context to the importer?

**Comment by Mgamerz** [comment]
- [x] Batch Editor - do not focus search box on load

**Comment by Mgamerz** [comment]
- [x] Document Merge Mod v2 changes (comment, compression, backwards compatibility, moddesc requirement)

**Comment by Mgamerz** [comment]
- [x] Handle closing of app while deployement is in progress
 - [x] Investigate significant performance stalling during references check. Can't repro.
 - [ ] Localization: ITA
 - [ ] Localization: RUS
 - [ ] Localization: DEU

**Comment by Mgamerz** [comment]
- [x] Mods missing modsite descriptor dialog - string.Join() is likely not adding - at the start.

**Comment by Mgamerz** [comment]
- [x] Handle main window closing when a subwindow is open such as batch editor or moddesc.ini editor
